app/app/urls.py
from django.contrib import admin
from django.urls import include, path

admin.site.site_header = 'ZaPFmaster3000'
admin.site.index_title = 'ZaPFmaster3000'
admin.site.site_title = 'ZaPFmaster3000'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('timetable.urls'), name='timetable'),
]

app/timetable/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path('', views.index, name='index'),
	path('aktable/', views.ak_table, name='ak_table'),
    path('timetable/', views.timetable, name='index'),
    path('database.json', views.timetable, name='index'),
]

app/timetable/models.py
from django.db import models

class Timeslot(models.Model):
    name = models.CharField(max_length=200)
    text = models.TextField(blank=True)
    place = models.CharField(max_length=200, blank=True)
    start = models.DateTimeField('start')
    end = models.DateTimeField('end')
    event_type = (
        ('food', 'food'),
        ('plenum', 'plenum'),
        ('ak', 'ak'),
        ('social', 'social'),
        ('else', 'else')
    )
    event_type = models.CharField(max_length=10, choices=event_type, default='ELSE')
    
    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Zeitslots"
        verbose_name = "Zeitslot"

class Room(models.Model):
    name = models.CharField(max_length=200, blank=True)
    hörsaal = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Räume"
        verbose_name = "Raum"

class AKSlot(Timeslot):
    backup = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "AK-Slots"
        verbose_name = "AK-Slot"

class AK(models.Model):
    akslot = models.ForeignKey(AKSlot, on_delete=models.CASCADE, blank=True, null=True )
    name = models.CharField(max_length=200, blank=True)
    short = models.CharField(max_length=200, blank=True)
    responsible = models.CharField(max_length=200, blank=True)
    room = models.ForeignKey(Room, on_delete=models.CASCADE, blank=True, null=True)
    url = models.CharField(max_length=1000, blank=True)
    workshop = models.BooleanField(default=False)
    backup = models.BooleanField(default=False)
    public_id = models.IntegerField(default=-1)

    published = models.BooleanField(default=False)
    kleine_fachschaften = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "AKs"
        verbose_name = "AK"

class RoomAssignment(models.Model):
    room = models.ForeignKey(Room, related_name='zuordnung', on_delete=models.CASCADE)
    group = models.ForeignKey(AK, related_name='zuordnung', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Raumzuordnungen"
        verbose_name = "Raumzuordnung"


class News(models.Model):
    message = models.TextField()
    time = models.DateTimeField()

    def __str__(self):
        return self.message

    class Meta:
        verbose_name_plural = "Nachrichten"
        verbose_name = "Nachricht"

app/timetable/forms.py
from django import forms

class ChangeForm(forms.Form):
    slot_1 = forms.IntegerField(label='Slot 1')
    slot_2 = forms.IntegerField(label='Slot 2')

app/timetable/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
import arrow
from django.http import JsonResponse
from .models import Timeslot, Room, AKSlot, AK, RoomAssignment, News
from .forms import ChangeForm
from django.contrib.admin.views.decorators import staff_member_required
import logging

logger = logging.getLogger(__name__)


def n_t(n, k):
    return (n%k, n//k)

def t_n(x1, x2, k):
    return x1 + x2* k

def wh(array, val):
    return np.argwhere(array==val)[0][0], np.argwhere(array==val)[0][1]

def index(request):
    template = loader.get_template('index.html')
    return HttpResponse(template.render({}, request))

def timetable(request):
    timeslots = Timeslot.objects.all()
    data = {
        'name': 'ZaPF App Database',
        'version': '2.0',
        'news': [{"date": arrow.get(n.time).humanize(locale='de_de'), "msg": n.message} for n in News.objects.all()],
        'slots' : [],
    }

    for t in timeslots:
        slot = {
            "test": arrow.get(t.start).to('Europe/Berlin').format(),
            "begin": arrow.get(t.start).to('Europe/Berlin').format('ddd HH:mm', locale='de_de'), 
            "end": arrow.get(t.end).to('Europe/Berlin').format('HH:mm'),
            "timestamp": int(arrow.get(t.start).timestamp),
            "finish": str(t.end)[0:10] + "T" + str(t.end)[11:19] + "+0000",  
            "name": t.name,
            "type": t.event_type
        }
        try:
            slot["place"] = t.place
        except:
            pass
            
        if hasattr(t, 'akslot'):
            slot["aks"] = []
            for ak in t.akslot.ak_set.all():
                if ak.published == False:
                    continue;
                ak_set = {
                    "name": ak.name,
                    "responsible": ak.responsible,
                    "room": ak.room.name,
                    "url": ak.url,
                    "short": ak.short,
                }
                if ak.published == True:
                    slot["aks"].append(ak_set)
        data["slots"].append(slot)
        #"aks" : [x for x in t.akslot.ak_set.all() if t]
    data['slots'].sort(key=lambda x: x['timestamp'])
    return JsonResponse(data)

def try_else(_input, _else):

    try:
        result = _input
        return result
    except:
        return _else

@staff_member_required
def ak_table(request):
    aks = AK.objects.all()
    rooms = Room.objects.all()
    akslots = AKSlot.objects.all()

    Räume = len(rooms)
    Slots = len(akslots)

    data = [[{"room": rooms[i].name, "akslot": "", "responsible": "", "name": "", "public_id": j*len(rooms)+i} for j in range(len(akslots))] for i in range(len(rooms))]

    if request.method == 'POST':
        form = ChangeForm(request.POST)
        if form.is_valid():
            slot_1 = int(form.cleaned_data['slot_1'])
            slot_2 = int(form.cleaned_data['slot_2'])  

            a = AK.objects.filter(public_id=slot_1)
            b = AK.objects.filter(public_id=slot_2)

            if len(a) == 1 and len(b) == 1:
                a[0].public_id, b[0].public_id = b[0].public_id, a[0].public_id
                a[0].akslot, b[0].akslot = b[0].akslot, a[0].akslot
                a[0].room, b[0].room = b[0].room, a[0].room
                a[0].save()
                b[0].save()
                print("a")

            
            """
            if len(a) == 1 and len(b) == 0:
                a[0].public_id = slot_2
                a[0].akslot = akslots[slot_2//Räume]
                a[0].raum = rooms[slot_2%Slots]
                a[0].save()
                print("b", a[0].akslot)

            if len(a) == 0 and len(b) == 1:
                b[0].public_id = slot_1
                b[0].akslot = akslots[slot_1//Räume]
                b[0].raum = rooms[slot_1%Slots]
                b[0].save()
                print("c")
            """
            

            return HttpResponseRedirect('/aktable/')

    rooms_result = []

    rooms_id_dict = {}
    for i, room in enumerate(rooms):
        rooms_id_dict[room.id] = i
        rooms_result.append(room.name)


    akslots_result = []

    akslots_id_dict = {}
    for i, akslot in enumerate(akslots):
        akslots_id_dict[akslot.id] = i 
        akslots_result.append(akslot.name)

    for i, ak in enumerate(aks):
        try:
            data[rooms_id_dict[ak.room.id]][akslots_id_dict[ak.akslot.id]]["room"] = ak.room.name
        except:
            pass

        try:
            data[rooms_id_dict[ak.room.id]][akslots_id_dict[ak.akslot.id]]["akslot"] = ak.akslot.name
        except:
            pass

        try:
            data[rooms_id_dict[ak.room.id]][akslots_id_dict[ak.akslot.id]]["responsible"] = ak.responsible
        except:
            pass

        try:
            data[rooms_id_dict[ak.room.id]][akslots_id_dict[ak.akslot.id]]["name"] = ak.name
        except:
            pass

        try:
            data[rooms_id_dict[ak.room.id]][akslots_id_dict[ak.akslot.id]]["short"] = ak.short
        except:
            pass

        try:
            data[rooms_id_dict[ak.room.id]][akslots_id_dict[ak.akslot.id]]["kleine_fachschaften"] = ak.kleine_fachschaften
        except:
            pass
            
        try:
            data[rooms_id_dict[ak.room.id]][akslots_id_dict[ak.akslot.id]]["ak"] = True
        except:
            pass

        try:
            data[rooms_id_dict[ak.room.id]][akslots_id_dict[ak.akslot.id]]["id"] = ak.id
        except:
            pass

        try:
            data[rooms_id_dict[ak.room.id]][akslots_id_dict[ak.akslot.id]]["public_id"] = ak.public_id
        except:
            pass

        # data[rooms_id_dict[ak.room.id]][akslots_id_dict[ak.akslot.id]] = {
        #     "room": ak.room.name,
        #     "akslot": ak.akslot.name,
        #     "responsible": ak.responsible,
        #     "name": ak.name,
        #     "short": ak.short,
        # }
    form = ChangeForm()
    x = {"data": data, "rooms": rooms_result, "akslots": akslots, 'form': form}

    template = loader.get_template('ak_table.html')
    return HttpResponse(template.render(x, request))

app/timetable/templates/ak_table.html
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script src='https://cdnjs.cloudflare.com/ajax/libs/dragula/$VERSION/dragula.min.js'></script>

<!--
<label for="slot_1">Slot 1: </label>
<input id="slot_1" type="number" name="slot_1" maxlength="100" required />
<label for="room_1">Room 1: </label>
<input id="room_1" type="number" name="room_1" maxlength="100" required />
<br>
<label for="slot_2">Slot 2: </label>
<input id="slot_2" type="number" name="slot_2" maxlength="100" required />
<label for="room_2">Room 2: </label>
<input id="room_2" type="number" name="room_2" maxlength="100" required />
-->

<table style="font-size: 10px;" class="table table-sm table-condensed" border="">
		<tr style="font-size: 130%; font-weight: bold;">
			<td></td>
			{% for akslot in akslots %}
				<td>{{ akslot }}</td>
			{% endfor %}
		</tr>

{% for room in data %}
	<tr>
	<td style="font-size: 130%" class="col-md-1">
		<b>{{room.0.room}}</b>
	</td>
	{% for akslot in room %}
		<td style="{% if akslot.kleine_fachschaften < 10%} background-color: rgba(255,0,0,0.{{akslot.kleine_fachschaften}}); {% else %}rgba(255,0,0,1){% endif %}" class="col-md-1">
				{% if akslot.ak == True %}
				<b style="font-size: 130%">({{ akslot.public_id }}) {{ akslot.name }}</b><br>
				{% if akslot.short != "-" %}
				{{ akslot.room }}<br>
				{{ akslot.responsible }}<br>
				{% endif %}
				{% else %}
				<b>({{ akslot.public_id }})</b>
				{% endif %}
				<!--{{ akslot.akslot }}-->
		</td>
	{% endfor %}
	</tr>
{% endfor %}
</table>

<form action="/aktable/" method="post">
    {% csrf_token %}
    <!--<label for="id_slot_1">Slot 1:</label>--><input style="margin-left: 10px; width: 60px;" type="number" name="slot_1" required="" id="id_slot_1" autofocus>
	<!--<label for="id_slot_2">Slot 2:</label>--><input style="width: 60px;" type="number" name="slot_2" required="" id="id_slot_2">
    <input type="submit" value="Submit">
</form>

app/timetable/templates/index.html
{% load static %}
<!Doctype html>
<html manifest="cache.manifest">
    <head>

        <title>ZaPF-App</title>

        <meta charset="utf-8" />

        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        
        <link rel="stylesheet" href="{% static 'style/normalize.css' %}" type="text/css" />
        <link rel="stylesheet" href="{% static 'style/fonts.css' %}" type="text/css" />
        <link rel="stylesheet" href="{% static 'style/layout.css' %}" type="text/css" />
<!--
        <link rel="stylesheet" href="{% static 'semantic-ui/semantic.min.css' %}" type="text/css" />
        <link rel="stylesheet" href="{% static 'semantic-ui/semantic.min.js' %}" type="text/css" />
-->
        <meta name="mobile-web-app-capable" content="yes"/>
        
        <meta name="theme-color" content="#7397c5"/>
        <link rel="shortcut icon" type="image/x-icon" href="{% static 'style/logo-favicon.ico' %}">
        <link rel="icon" sizes="192x192" href="{% static 'style/logo-app-192.png' %}">

    </head>
    <body>

        <!-- 1. Load libraries -->
        <!-- IE required polyfills, in this exact order -->
        <script src="{% static '3dparty/es6-shim.min.js' %}"></script>
        <script src="{% static '3dparty/system-polyfills.js' %}"></script>
        <script src="{% static '3dparty/shims_for_IE.js' %}"></script>   
        <script src="{% static '3dparty/angular2-polyfills.js' %}"></script>
        <script src="{% static '3dparty/system.src.js' %}"></script>
        <script src="{% static '3dparty/Rx.js' %}"></script>
        <script src="{% static '3dparty/angular2.js' %}"></script>
        <script src="{% static '3dparty/http.js' %}"></script>
        <script src="{% static 'ngtweet.min.js' %}"></script>
        <!-- 2. Configure SystemJS -->
        <script>
            System.config({
                packages: {        
                    app: {
                        format: 'register',
                        defaultExtension: 'js'
                    }           
                }
            });
            System.import('{% static "app/main.js" %}')
                .then(null, console.error.bind(console));
        </script>

        <!-- 3. Load App -->
        <div class="appcomponent"></div>
        <div style="text-align: center;">
          <small style="margin-bottom: 30px;">
            <a href="http://ethylomat.de/datenschutz">Datenschutzerklärung</a> // 
            <a href="http://ethylomat.de/impressum">Impressum</a>
          </small>
        </div>


    </body>
</html>